### ISSUE TITLE
g++: error: ......No such file or directory

### ISSUE THREAD

**Issue by ZhijiangTang** [aman-goel/avr#13]
There is a bug here showing ```No such file or directory```
![image-20240204132006958](https://github.com/aman-goel/avr/assets/106744260/903d6f14-6e02-478d-aaf2-db9ddce2165a)

**Comment by ZhijiangTang** [comment]
When checking the code, it was found that the error occurred when compiling ```/avr/src/reach```. Further inspection of the `Makefile` file revealed that there is a problem with this code:

![image-20240204132536466](https://github.com/aman-goel/avr/assets/106744260/96742116-69c0-4b1e-bcc9-c39b42d07ec7)

The main issues include two points:

- `BT_LIB += $(BT_DIR)/deps/btor2tools/build/libbtor2parser.a`, there is an overlap problem between `$(BT_DIR)` and `deps/btor2tools/build/libbtor2parser.a`.
- `cadical` is missing in the `deps` folder and needs to be installed

**Comment by ZhijiangTang** [comment]
Solution:

All the following operations are in the project `avr/` directory

1. Download `cadical`

```shell
cd deps
git clone https://github.com/arminbiere/cadical.git
```
2. Install according to `cadical readme`

```shell
cd /deps/cadical
./configure
make
```

3. Modify the problematic area (**lines 37-45**) of the `Makefile` in `/src/reach` to the following

```makefile
ifeq ($(ENABLE_BT), 1)
  BT_DIR = $(DEPS)/boolector
  BT_LIB = $(BT_DIR)/build/lib/libboolector.a
  BT_LIB +=  $(DEPS)/btor2tools/build/lib/libbtor2parser.a
  BT_LIB +=  $(DEPS)/cadical/build/libcadical.a
  INCLUDE += -I$(BT_DIR)/src
  LINKLIBS += $(BT_LIB)
  CFLAGS += -D_BT
endif
```

Then recompile in `/src/reach`

```shell
cd /src/reach
make
```

**Comment by ZhijiangTang** [comment]
@aman-goel This `deps` dependency is missing and the `/src/reach/Makefile` bug. Please take a look at it to help modify it.

**Comment by aman-goel** [comment]
(Apologies for my super late response)

Thanks for raising the issue.
- Bto2tools library path is now corrected.
- Cadical is installed when installing Boolector [here](d858a26bd3ce)
