### ISSUE TITLE
Wrong path for libbtor2parser.a in reach's Makefile

### ISSUE THREAD

**Issue by LH104729** [aman-goel/avr#14]
Line 40 of ./src/reach/Makefile should be

`  BT_LIB += $(BT_DIR)/deps/btor2tools/build/lib/libbtor2parser.a`

instead of

`  BT_LIB += $(BT_DIR)/deps/btor2tools/build/libbtor2parser.a`

**Comment by aman-goel** [comment]
(Apologies for my super late response)

Thanks for raising the issue. Bto2tools library path is now corrected.
