### ISSUE TITLE
Assertion failed when using Boolector as backend solver

### ISSUE THREAD

**Issue by nianzelee** [aman-goel/avr#15]
- Version: dbc3371abe7b284db61636fc2b5c60f2922d17d7
- Environment: Ubuntu 22.04 (Linux kernel 6.5.0-17-generic)
- Command line: `/avr.py --bmc --bin ./build/bin-boolector --timeout 900 --memout 15000 counter_v.btor2.txt`
  - AVR was compiled with Boolector, and binaries are put under `./build/bin-boolector/`
  - Input file [counter_v.btor2.txt](https://github.com/aman-goel/avr/files/14223690/counter_v.btor2.txt) attached
- Result
```shell
Copyright (c) 2016 - Present  Aman Goel and Karem Sakallah, University of Michigan
	(output dir: output/work_test)
	(frontend: btor2)
	(property: all (1 assertions))
	(problem size: 4 bits)
	(abstraction: sa+uf)
reach: reach_bt.cpp:1178: virtual void _bt::bt_API::assert_distinct_constants(): Assertion `0' failed.
```

**Comment by aman-goel** [comment]
Thanks for bringing this up!

Support for Boolector and MathSAT 5 for abstract domain queries were experimental only. Going forward, Yices 2 is the default SMT backend for all abstract domain queires, and flags `BACKEND_*` in reach_backend.h will only be configuring SMT solver for the bit vector (i.e., concrete domain) queries.

By default, AVR uses `sa+uf` (check Notes for Pro Users in AVR readme) as abstraction, even for BMC/K-ind. To perform concrete BMC/K-IND/Word-IC3 (i.e., without any uninterpreted functions abstraction), pass argument `--abstract sa`.

**Comment by nianzelee** [comment]
Thanks for the help. The task can be solved by disabling the UF abstraction.
